on:
  workflow_dispatch:
    inputs:
      username:
        description: "A username passed from the caller workflow"
        default: "john-doe"
        required: false

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The value from github.event.inputs.username is ${{ github.event.inputs.username }}
